name: Github CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"
          miniconda-version: "latest"
          activate-environment: base
          auto-update-conda: false
          use-mamba: false
          update-conda: false
          channels: conda-forge,bioconda,defaults


      - name: Verify Python
        run: |
          which python
          python --version

      - name: Install Codon
        run: |
          mkdir -p ${HOME}/.codon
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz \
            | tar zxvf - --strip-components=1 -C ${HOME}/.codon
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz \
            | tar zxvf - -C ${HOME}/.codon/lib/codon/plugins
          echo "${HOME}/.codon/bin" >> $GITHUB_PATH

      - name: Install Python package dependencies
        run: |
          pip install find_libpython
          export CODON_PYTHON=$(find_libpython)
          echo "CODON_PYTHON=${CODON_PYTHON}" >> $GITHUB_ENV

          pip install matplotlib biotite  # week1/week3
          pip install igv-notebook pandas jupyter nbconvert

      - name: Install system packages (week5)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake make gcc perl \
            zlib1g-dev libbz2-dev liblzma-dev \
            libcurl4-gnutls-dev libssl-dev libdeflate-dev
          sudo apt-get install -y samtools bcftools

      - name: Install week6 conda + pip deps
        run: |
          conda install -y pandas simpleaf salmon boost-cpp=1.85
          pip install pyroe igraph leidenalg celltypist mygene

      - name: Week 6 Notebook Execution
        run: |
          jupyter nbconvert --to notebook --execute week6/week6.ipynb
